---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend
spec:
  replicas: {{ .Values.defaults.backend.replicas }}
  selector:
    matchLabels:
      app: my-app-backend
  template:
    metadata:
      labels:
        app: my-app-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.defaults.backend.image }}
        ports:
        - containerPort: {{ .Values.defaults.backend.service.port }}