---
apiVersion: v1
kind: Service
metadata:
  name: my-app-frontend
spec:
  type: {{ .Values.defaults.frontend.service.type }}
  selector:
    app: my-app-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.defaults.frontend.service.port }}
      targetPort: {{ .Values.defaults.frontend.service.port }}